export enum AuthenticationErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  UNAUTHORIZED = 'UNAUTHORIZED',
}

export enum ValidationErrorCode {
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_UUID = 'INVALID_UUID',
  REQUIRED_FIELD = 'REQUIRED_FIELD',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  INVALID_DATE = 'INVALID_DATE',
  NEGATIVE_VALUE = 'NEGATIVE_VALUE',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
}

export enum ResourceNotFoundErrorCode {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
}

export enum ForbiddenErrorCode {
  INVALID_OWNERSHIP = 'INVALID_OWNERSHIP',
  ACCESS_DENIED = 'ACCESS_DENIED',
}

export enum BusinessRuleErrorCode {
  SUBCATEGORY_REQUIRES_CATEGORY = 'SUBCATEGORY_REQUIRES_CATEGORY',
  CATEGORY_TYPE_MISMATCH = 'CATEGORY_TYPE_MISMATCH',
  CANNOT_DELETE_CATEGORY_WITH_TRANSACTIONS = 'CANNOT_DELETE_CATEGORY_WITH_TRANSACTIONS',
  CANNOT_DELETE_BANK_ACCOUNT_WITH_TRANSACTIONS = 'CANNOT_DELETE_BANK_ACCOUNT_WITH_TRANSACTIONS',
}

export enum SystemErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',
}

export type ErrorCode =
  | AuthenticationErrorCode
  | ValidationErrorCode
  | ResourceNotFoundErrorCode
  | ForbiddenErrorCode
  | BusinessRuleErrorCode
  | SystemErrorCode;
