export const REPOSITORY_TOKENS = {
  USERS: Symbol('USERS'),
  BANK_ACCOUNTS: Symbol('BANK_ACCOUNTS'),
  TRANSACTIONS: Symbol('TRANSACTIONS'),
  CATEGORIES: Symbol('CATEGORIES'),
  SUBCATEGORIES: Symbol('SUBCATEGORIES'),
};
