version: '3.8'

services:
  db:
    container_name: pg
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
